### ISSUE TITLE
How do you create an sdl.AudioCallback function?

### ISSUE THREAD

**Issue by gcatlin** [veandco/go-sdl2#127]
I don't understand how to create my own callback function of type `sdl.AudioCallback` to pass to `sdl.AudioSpec`. Can anyone provide a simple example?

I was able to get something to compile, but I don't think it's valid -- the callback doesn't get called:
```go
package main

import (
	"fmt"
	"time"
	"unsafe"

	"github.com/veandco/go-sdl2/sdl"
)

func main() {
	cb := func(unsafe.Pointer, *uint8, int) {
		fmt.Println("callback called")
	}
	spec := &sdl.AudioSpec{
		Freq:     4800,
		Format:   sdl.AUDIO_S16LSB,
		Channels: 2,
		Samples:  1024,
		Callback: sdl.AudioCallback(unsafe.Pointer(&cb)),
	}
	sdl.OpenAudio(spec, nil)
	fmt.Printf("%+v\n", spec)
	sdl.PauseAudio(0)
	time.Sleep(2 * time.Second)
}
```

For reference:

audio.go:
```go
type AudioCallback C.SDL_AudioCallback
```

SDL_audio.h (SDL 2.0.3):
```c
/**
 *  This function is called when the audio device needs more data.
 *
 *  \param userdata An application-specific parameter saved in
 *                  the SDL_AudioSpec structure
 *  \param stream A pointer to the audio data buffer.
 *  \param len    The length of that buffer in bytes.
 *
 *  Once the callback returns, the buffer will no longer be valid.
 *  Stereo samples are stored in a LRLRLR ordering.
 */
typedef void (SDLCALL * SDL_AudioCallback) (void *userdata, Uint8 * stream, int len);
```

**Comment by krux02** [comment]
Sorry, to tell you this, but this is a very hard part to wrap and nobody did it properly yet. The problem is,  that SDL_AudioSpec is a struct that contains a pointer to a C.Compatible function. That is nice for a C api, but not easy to port, since functions from go canst be cast to a C compatible function pointer. But it is poissible to write a function in go that can be cast into an AudioCallback:

    //void MyCallback(void *userdata, Uint8 * stream, int len);
    import "C"

    //export MyCallback
    func MyCallback(userdata unsafe.Pointer, stream *C.Uint8, length C.int) {
        [...]
    }

now `C.MyCallback` should ba a valiid SDL_AudioCallback and therefore be compatible. sorry this api is far from ideal, but pull requests that make it nicer are always welcome. There's no "please don't break existing code" rule for this port yet.

**Comment by gcatlin** [comment]
Thank you! I need to think more on the API for `sdl.AudioCallback`s . In the meantime, I'll submit a PR for an example.
