### ISSUE TITLE
Creating a stable binding release

### ISSUE THREAD

**Issue by velovix** [veandco/go-sdl2#131]
The README states that go-sdl2 is not stable right now. Is there anything that needs to happen before someone can tag a version number that we can vendor to?

**Comment by jackyb** [comment]
I personally want a full test suite first before committing to a stable release, just to make sure everything is working and tested before labeling it as stable.

**Comment by velovix** [comment]
Fair enough. As you may already know, SDL2 comes with a set of tests. They'd have to be ported, but would that fit the bill?

**Comment by jackyb** [comment]
That's a good idea! Yes, I believe the package is complete if we manage to recreate their tests.

**Comment by velovix** [comment]
Great! I'll see what I can do to make that happen.

**Comment by krux02** [comment]
I am not sure if just porting all their tests to go really worth the time. Especially, because go-sdl is just a wrapper. But there is something that needs to be solved that I think is a little bit more urgent.

For example the API at it's current state has some issues, that do not have a solution.

    func (rect *Rect) IntersectLine(X1, Y1, X2, Y2 *int) bool {
        X1 := (*C.int)(unsafe.Pointer(X1))
        [...]

in this code an *int is cast to an *C.int. On 32 bit systems both int and C.int are 32 signed bit integers. On 64 bit systems the C.int is 32 bit and the int form go is 64 bit. On system with little endian (x64) this is not a problem because ENDIAN!!!, it screws you up on big endian systems.

This problem needs discussion, because it influences the api design. Often where you have an sdl call that takes an int, you do not want to force the user of go-sdl to explicitly cast their int to int32, to make it compatible. But using int everywhere would make the Rect struct binary incompatible with the SDL_Rect struct.

**Comment by jangler** [comment]
I agree that porting all the SDL2 tests is overkill. Whether SDL2 works is SDL2's problem; we just should be testing whether the wrapper works properly.

@krux02, maybe this is a topic for a different issue, but how about casting the `int`s to `int32`s inside the function?

**Comment by velovix** [comment]
I have to say, porting the SDL tests definitely ended up looking like more work than I originally thought. So long as this is a more or less a discussion thread, how thin are these bindings supposed to be? I was surprised to see LoadWAV, for instance, requiring I pass it a pointer, C-style. Even pretty thin wrappings tend to turn that kind of thing into a slice, and I think it makes more sense from an API design perspective for one library to deal with the unsafe stuff instead of having every user do it and potentially get it wrong. Was this intentional?

**Comment by jangler** [comment]
I think there are definitely places in the library where little things like that can be made more Go-like and less C-like, but I'm not sure if `LoadWAV()`'s `audioBuf` is a prime candidate. I don't think Go exposes a way to construct a slice from a pointer like that without an O(n) copy operation. That being said, I see no reason for `audioLen` to be a parameter instead of a return value.

**Comment by jackyb** [comment]
@jangler Surface.Pixels() method demonstrates how to construct array from C pointer without copying.

**Comment by jangler** [comment]
Ah, cool. In that case I agree that the function should return a slice instead of filling `audioBuf` and `audioLen`.

**Comment by jackyb** [comment]
I just made a quick modification to the functions. Somebody test it!

**Comment by velovix** [comment]
I think casting in the function from int to int32 would be the right choice. C doesn't actually guarantee the size of an int to be 32-bit, I believe, so technically having the Go function accept int32's isn't entirely correct. In practice, C ints are 32-bit, but I still think it makes more sense for that to be an implementation detail.

**Comment by krux02** [comment]
on 16 bit systems a C int is 16 bit, but as far as I know SDL2 doesn't support any 16 bit systems. But I couldn't find an official list of supported platforms.

**Comment by velovix** [comment]
According to [this list](https://wiki.libsdl.org/MigrationGuide#Dead_platforms), the supported platforms are Windows (XP and later), Linux, Mac OS X, iOS, and Android, so you are correct (though I guess there are 16-bit Linux distributions). Still, the API would be easier to work with if the user didn't have to typecast their ints themselves every time they call IntersectLine
