### ISSUE TITLE
sdl_mixer wrapper requires MIDI support

### ISSUE THREAD

**Issue by stqn1** [veandco/go-sdl2#158]
When I try to install the sdl2-mixer wrapper, it fails:
```
$ go get -v github.com/veandco/go-sdl2/sdl_mixer
github.com/veandco/go-sdl2/sdl_mixer
# github.com/veandco/go-sdl2/sdl_mixer
/tmp/go-build257741081/github.com/veandco/go-sdl2/sdl_mixer/_obj/sdl_mixer.cgo2.o: In function `_cgo_2986dbf602a7_Cfunc_Mix_EachSoundFont':
code/go/src/github.com/veandco/go-sdl2/sdl_mixer/sdl_mixer.go:97: undefined reference to `Mix_EachSoundFont'
/tmp/go-build257741081/github.com/veandco/go-sdl2/sdl_mixer/_obj/sdl_mixer.cgo2.o: In function `_cgo_2986dbf602a7_Cfunc_Mix_GetSoundFonts':
code/go/src/github.com/veandco/go-sdl2/sdl_mixer/sdl_mixer.go:350: undefined reference to `Mix_GetSoundFonts'
collect2: error: ld returned 1 exit status
```
The reason seems to be that my version of sdl2-mixer was built without MIDI support.
Would it be possible to make MIDI support optional?

**Comment by jackyb** [comment]
Hi, I applied a patch that allows you to disable MIDI support through build tag.

`go install -tags nomidi`

**Comment by stqn1** [comment]
Excellent, thanks! I ran "go get -v -u -tags nomidi github.com/veandco/go-sdl2/sdl_mixer" and got no error, so it seems it worked :).

**Comment by jkearse3** [comment]
Hello! It seems this patch has broken installation of the bindings. When using "go get -v github.com/veandco/go-sdl2/sdl_mixer ", I get the following errors:

../../veandco/go-sdl2/sdl_mixer/midi.go:16: undefined: unsafe in unsafe.Pointer
../../veandco/go-sdl2/sdl_mixer/midi.go:29: undefined: unsafe in unsafe.Pointer

Is it because of a missing import?

Thanks!

**Comment by jackyb** [comment]
Seems so! I fixed it in the latest patch. Sorry about that.
