### ISSUE TITLE
Not a issue. Question. pkg/image vs. go sdl for image processing.

### ISSUE THREAD

**Issue by billyninja** [veandco/go-sdl2#166]
Suppose I want to make a webservice for simple image manipulation: crop, resize, rotate, filters, concatenating images etc.

Which library would give the highest image throughput? go-sdl2 or pkg/image?

**Comment by jackyb** [comment]
Definitely use other libraries like [imagick](https://github.com/gographics/imagick) which is a C binding to the popular ImageMagick or native Go solution like [imaging](https://github.com/disintegration/imaging). By pure reputation, ImageMagick should be faster but I'm not sure how much overhead the binding has on it.

**Comment by krux02** [comment]
I thik it doesn't matter that much, because the bottleneck will be the internet. Images can be big, and the operations you want to do on them are very trivial. If you really want high performance, you should prevent completely that the images are on your server. There are options, that you can run imageMagic in the browser on the client side (asm.js or nativeclient). Then you can prevent completely the traffic from sending and receiving images.
