### ISSUE TITLE
Can't build sdl_mixer.go with gccgo 5.3.0

### ISSUE THREAD

**Issue by tycho** [veandco/go-sdl2#167]
```
$ go version
go version go1.4.2 gccgo (GCC) 5.3.0 linux/amd64
$ go get -v github.com/veandco/go-sdl2/sdl_mixer
github.com/veandco/go-sdl2/sdl_mixer
# github.com/veandco/go-sdl2/sdl_mixer
gocode/src/github.com/veandco/go-sdl2/sdl_mixer/sdl_mixer.go:83:2: error: embedded type may not be a pointer
  unsafe.Pointer
  ^
```

**Comment by akovaski** [comment]
Interesting,
https://github.com/golang/go/issues/6357
but you could replace it with any typedef since all it ever uses is the pointer to the object, never the object itself (I think).

looking at the defition of the struct that is actually used (unofficial mirror https://github.com/aduros/SDL_mixer/blob/master/music.c), it looks like it actually is different depending on how it's compiled (I don't know how C unions work).

Anyways, replacing that struct definition with
````go
type Music struct{}
````
should be fine

**Comment by tycho** [comment]
Hi @akovaski! A C union is actually not too tough, e.g.:
```
union {
    Foo *foo;
    Bar *bar;
} data;
```
The union above makes the variables 'foo' and 'bar' reside at the same memory location (the size of the memory used by the union itself depends on the inputs (the largest of them determines the memory reserved for it). With the above union you can use either 'data.foo' (type Foo*) or 'data.bar' (type Bar*) to refer to the value stored there, depending on what type you actually want to be using. So the union in struct _Mix_Music is always just a pointer to the data for that type of music file. The conditional compilation basically just adds or removes other types in the union, but shouldn't change the structure's size since it's always a pointer-size value anyway.

Incidentally, while I'm kind of a C whiz, I'm a Go flunkie, so I have no idea what doing `type Music struct{}` is actually doing. Looks to me like a declaration of a type of struct with no members? I need to read up on how the Go<->C interop works.

**Comment by akovaski** [comment]
Ok, I didn't notice they were all pointers (and thus didn't notice the union would take up just the space of 1 pointer in the struct).

Yes, that is an empty struct... (If you look at the methods of the 'Music' type, they all just use a pointer to the Music type and don't actually acre what's in it, or even about the size of the struct, which is why I suggested it as a potential replacement). Go structs work similarly to C structs. In practice they seem to have the same layouts in memory, [though I don't think Go or C makes any promises on memory layout.](https://groups.google.com/forum/#!topic/golang-nuts/1BlZDNBLiAM) (It might be a good idea to replace the couple times a cast is done from a C struct to a Go struct in this library, but I'm not doing it :))

Anyways, the safest approach is probably as follows
```go
type Music C.Mix_Music
```

**Comment by tycho** [comment]
Using `type Music C.Mix_Music` seems to work. I tested the 'audio' and 'audio_mp3' examples and they worked as well, built with `go build -gccgoflags '-lSDL2_mixer -lSDL2'`.

**Comment by akovaski** [comment]
huh, I'm surprised that you need to pass those link flags.

Anyways, feel free to send a push request with that change, I'm sure Jacky would accept it.

**Comment by tycho** [comment]
I think gccgo is a bit of a special snowflake. There are advantages though, like all the years of development that have gone into GCC's auto-vectorization. I'll get a pull request up in a minute.
