### ISSUE TITLE
Color.Uint32() probably implemented incorrectly

### ISSUE THREAD

**Issue by faiface** [veandco/go-sdl2#202]
Currently, `Color.Uint32()` returns an integer in format `#00RRGGBB`.
However, functions in SDL2_gfx, such as `FilledPolygonColor` require `#AABBGGRR`.
I am not sure if this is a bug, or SDL2_gfx just use some crazy representation, however, `Color.Uint32()` doesn't produce usable results in this case.

**Comment by veeableful** [comment]
Hi faiface, it seems like SDL2_gfx doesn't use the same format as SDL2 itself according to the a test I did using both C and Go versions of filledPolygonColor() and SDL_FillRect(). The former function produces blue while the latter produces red using 0xFFFF0000.

However, I did discover that the binding doesn't use the A value for some reason which I fixed in the latest commit :+1:

**Comment by faiface** [comment]
Ok, that's funny. So I have to make my own func for that, but that's no problem. Thanks anyway ;)
Guess the issue can be closed.

**Comment by veeableful** [comment]
If you have a suggestion on how to make it easier, we could put it into the binding. I'm thinking of either changing all the uint32 into sdl.Color which is then converted internally _or_ provide a function for users that does the conversion. Which one would be more convenient for you?

**Comment by faiface** [comment]
I like the first option alot. It kinda breaks the "isomorphism" between the binding and the original, but I guess that's broken anyway already :D. But it adds a lot of convenience, which is good. Having two functions would work (that's what I have right now), but would be cumbersome in the library I think.

**Comment by veeableful** [comment]
Alright then, I've updated gfx to use sdl.Color instead! :grin:

**Comment by faiface** [comment]
Great! :D And thanks for a very responsive feedback.

**Comment by veeableful** [comment]
You're welcome!
