### ISSUE TITLE
How to compile for ARM?

### ISSUE THREAD

**Issue by prsolucoes** [veandco/go-sdl2#213]
How to compile for ARM?

Im trying compile the example on README for ARM:

```
env GOOS=linux GOARCH=arm go build
# github.com/veandco/go-sdl2/sdl
../../Developer/workspaces/go/src/github.com/veandco/go-sdl2/sdl/yuv_sw_c.go:17: undefined: Surface
../../Developer/workspaces/go/src/github.com/veandco/go-sdl2/sdl/yuv_sw_c.go:18: undefined: Surface
```

**Comment by veeableful** [comment]
Hi @prsolucoes, I never cross-compiled SDL to ARM but I'm thinking if you compiled and installed SDL2 for ARM, you should be able to compile go-sdl2 for ARM too. Perhaps this guide can tell you how to do it https://how-to-build-for-arm.wikispaces.com/sdl2

**Comment by prsolucoes** [comment]
Hi, 

I have installed using brew on my mac, but i have the version for ARM already compiled.

You can download here:
https://www.dropbox.com/s/5a8um05bymc8pgg/sdl2.zip?dl=0

I only dont know how i can do it using go. In c++ you can pass -I, -i, -L to include and libs args.

Can you help me?

**Comment by veeableful** [comment]
Hiya, sorry for late reply! Hope you had a merry christmas and happy new year!

I haven't tried it myself because I'm missing the right GCC toolchain but I think you might be able to do it with the right commands. Something like this might work: `CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOARCH=arm GOARM=5 go build -a`. I found out about the ARM version of the library you gave me through `readelf -A` and set it through the GOARM environment variable. I believe you still need a Linux machine though.
