### ISSUE TITLE
Event interface has no exported fields?

### ISSUE THREAD

**Issue by Pixdigit** [veandco/go-sdl2#259]
I might just getting this wrong how to use SDL_Event but how come that when I execute
```
a := sdl.PollEvent()
if a != nil {
    fmt.Printf("%+v\n", a)
}
```
I get `&{Type:512 Timestamp:154 WindowID:2 Event:1 _:0 _:0 _:0 Data1:0 Data2:0}`
But when I try to
```
a := sdl.PollEvent()
if a != nil {
    fmt.Println(a.Type)
}
```
it raises `a.Type undefined (type sdl.Event is interface with no methods)`.
What do I need to do? Or is this actually an error in `go-sdl2`?
(By the way I feel sorry for always asking here, is there a better place to ask such questions?
Or are there enough people knowing go-sdl2 on StackOverflow?)

**Comment by veeableful** [comment]
Hi @Pixdigit, no worries you can ask here :)

`sdl.PollEvent()` returns an `interface{}` where you can then use type assertion to match the type. You can see an example in `examples/events/events.go` to see how it is done. This is because the native version uses a union instead of struct so we can't just easily translate it to Go.
