### ISSUE TITLE
Unable to set HapticDirection.dir

### ISSUE THREAD

**Issue by theGeekPirate** [veandco/go-sdl2#315]
dir is unexported (https://github.com/veandco/go-sdl2/blob/master/sdl/haptic.go#L46) and has no methods to set it with, so we're currently unable to use it.

https://wiki.libsdl.org/SDL_HapticDirection

**Comment by malashin** [comment]
Hey @theGeekPirate, Dir is exported now. Thank you for your feedback.

I am wondering if anyone has actually used the bindings for haptics. Either I am missing something or there is no way to actually create/update the HapticEffect. I had to update the C pointer for this to work:
```go
err := sdl.Init(sdl.INIT_EVERYTHING)
if err != nil {
	panic(err)
}

joy := sdl.JoystickOpen(0)

h, err := sdl.HapticOpenFromJoystick(joy)
defer h.Close()

e := sdl.HapticConstant{
	Type:      sdl.HAPTIC_CONSTANT,
	Direction: sdl.HapticDirection{Type: sdl.HAPTIC_CARTESIAN, Dir: [3]int32{-1, 0}},
	Length:    1000,
	Level:     32767,
}

he := sdl.HapticEffect{}
*((*sdl.HapticConstant)(unsafe.Pointer(&he[0]))) = e

id, err := h.NewEffect(&he)
if err != nil {
	panic(err)
}
defer h.DestroyEffect(id)

h.RunEffect(id, 1)

time.Sleep(2 * time.Second)
```

We should probably make functions to update HapticEffect with actual effects or think of some other way of creating them in the first place.

This one might be redundant in that case, not sure what it is used for:
```go
func (he HapticEffect) SetType(typ uint16) {}
```

**Comment by theGeekPirate** [comment]
From both my PS3 and XBOne controllers using your code:

```panic: Haptic: Effect not supported by haptic device.```

Tried changing the Type just in case, but to no avail.

My original goal was to have the left/right sides rumble independently.

Have you been able to get it working with an sdl.GameController?

**Comment by theGeekPirate** [comment]
I should probably mention that a regular ```haptic.RumblePlay()``` does work on both controllers.

**Comment by theGeekPirate** [comment]
Interesting, I wonder if your first example doesn't work because SDL2 is detecting it as an XInput device instead of an XB One controller.

Thanks for pasting working examples, made testing much easier!

**Comment by theGeekPirate** [comment]
Also, is there any reason you use the sdl.Joystick instead of an sdl.GameController?

Best practice, or preference?

**Comment by malashin** [comment]
@theGeekPirate 
> Interesting, I wonder if your first example doesn't work because SDL2 is detecting it as an XInput device instead of an XB One controller.

As far as I remember is that if you open it as gamepad instead of joystick it will recognize it as Xbox One Contoller. But the example doesn't work because the gamepad doesn't support those effects. XInput is Microsofts API for Xbox Controller, and many other gamepads use it now, instead of legacy DirectInput.

**Comment by theGeekPirate** [comment]
Oh neat, thanks for the information! FWIW, using sdl.GameController still returns the Name as ```XInput```.

**Comment by malashin** [comment]
@theGeekPirate 
> Also, is there any reason you use the sdl.Joystick instead of an sdl.GameController?

The first example was used to test directional effects and since they don't work with gamepads I had to use joystick.

Joysticks are all the peripheral devices like wheels, joysticks, pedals, gamepads. GameController is still a joystick but have different functions and you might not find needed one in GameController methods. You are better off opening it as a GameController and returning sdl.Joystick with this function if needed:

```go
// Joystick returns the Joystick ID from a Game Controller. The game controller builds on the Joystick API, but to be able to use the Joystick's functions with a gamepad, you need to use this first to get the joystick object.
// (https://wiki.libsdl.org/SDL_GameControllerGetJoystick)
func (ctrl *GameController) Joystick() *Joystick {}
```

HapticOpenFromJoystick() was used in the examples, but there is no equivalent of it for GameControllers. Also I did not need any GameController methods, so it was not opened as one.
```go
// HapticOpenFromJoystick opens a haptic device for use from a joystick device.
// (https://wiki.libsdl.org/SDL_HapticOpenFromJoystick)
func HapticOpenFromJoystick(joy *Joystick) (*Haptic, error) {
	haptic := (*Haptic)(unsafe.Pointer(C.SDL_HapticOpenFromJoystick(joy.cptr())))
	if haptic == nil {
		return nil, GetError()
	}
	return haptic, nil
}
```

**Comment by malashin** [comment]
There is no need for sdl.HapticEffect{} now, pass pointer to sdl.HapticLeftRight{} instead of it.

Check https://github.com/veandco/go-sdl2/pull/316 for details.

**Comment by theGeekPirate** [comment]
Your commit logs and issue comments are unparalleled.

Thanks for the great work!

**Comment by xpander69** [comment]
Same issue here. FFB doesn't work
log reveals that:

```
107214.718:002f:006d:err:dinput:effect_Download SDL_HapticNewEffect failed (Effect type 128): Haptic: Effect not supported by haptic device.
107214.734:002f:006d:err:dinput:effect_Download SDL_HapticNewEffect failed (Effect type 128): Haptic: Effect not supported by haptic device.
```

i tried to search what this effect type 128 is, but didnt find anything. I guess i have to downgrade to older version also. The Game works superbly other than that. Just need my FFB

**Comment by veeableful** [comment]
Hi @xpander69, could you provide a minimal code example and details about your setup? I'll see if I can try to reproduce the problem. Sorry for the late response..

**Comment by malashin** [comment]
The issue is most likely in the SDL itself and not in the bindings.

Haptics are fairly weird and each device works differently on different operating systems. I got Xbox One Controller and the list of supported effects is different on Windows and Linux.

I did an example quite a while ago that let's you test which effects are supported:
https://github.com/veandco/go-sdl2-examples/blob/4298a5894b3ec15532eb78de70c71a528095865e/examples/haptic/haptic.go

**Comment by xpander69** [comment]
@veeableful what you have in mind with the code example? btw i reported in another issue https://github.com/ValveSoftware/Proton/issues/908#issuecomment-445087179

The effect that failed does not cause the FFB not to work in the newer version of the game, older version of the game has the same error messages in proton log, but FFB still works. 

I have logitech Driving Force GT (my G920 should arrive this week)
