### ISSUE TITLE
Add const definitions for SDL_TRUE and SDL_FALSE

### ISSUE THREAD

**Issue by grkuntzmd** [veandco/go-sdl2#323]
When calling `(*sdl.Surface).SetColorKey()`, the first argument, an `int`, needs to be either `SDL_TRUE` or `SDL_FALSE`. (See https://wiki.libsdl.org/SDL_SetColorKey).

These are defined in `SDL/SDL_stdinc.h` and `SDL2/SDL_stdinc.h`, but not passed through to the Go code.

**Comment by malashin** [comment]
@grkuntzmd you can use `1` as `SDL_TRUE`, `0` as `SDL_FALSE`.
```go
s.SetColorKey(1, sdl.MapRGB(s.Format, 0, 255, 255))
```
I'm gonna rewrite it to use golangs `boolean` instead of `int` later on.

**Comment by malashin** [comment]
@grkuntzmd 
I've updated the rest of the functions that still used `int` instead of `bool` in the core SDL bindings.
+ `Surface.SaveBMPRW()` requires (\*RWops, bool) instead of (\*RWops, int)
+ `Surface.SetColorKey()` requires (bool, uint32) instead of (int, uint32)
+ `Surface.SetRLE()` requires bool instead of int
+ `LoadBMPRW()` requires (\*RWops, bool) instead of (\*RWops, int)

```go
s.SetColorKey(true, sdl.MapRGB(s.Format, 0, 255, 255))
```

**Comment by grkuntzmd** [comment]
That works. Thanks.
