### ISSUE TITLE
Keep names in go-sdl2 and upstream SDL the same where possible

### ISSUE THREAD

**Issue by mbenkmann** [veandco/go-sdl2#334]
I've noticed that e.g. GetAxis() was renamed to Axis(). Please don't forget that go-sdl2 is not its own library but a wrapper around SDL. Having a 1:1 mapping between upstream SDL names and go-sdl2 names is WAY MORE IMPORTANT than conforming with the OPINIONS about Go function naming of a few old men.

Besides, the change broke client code for no good reason.

**Comment by tanema** [comment]
Absolutely not, this is a wrapper around SDL but should conform to community best practices. If you start making exceptions like that you get inconsistent code all over the place. That is the exact reason the Go team has put so much effort into documenting and tooling Go best practices.

**Comment by mbenkmann** [comment]
Best practices for a wrapper is to keep the original names. You may live in your happy little Go world all the time, but other people live in a larger world. I also use SDL in C and in Python. The function is called SDL_JoystickGetAxis() in C. It's pygame.joystick.Joystick.get_axis() in Python. And it used to be sdl.Joystick.GetAxis() in Go.

THAT is best practice.

Keeping a name once people have started using your library. THAT is best practice, too.

**Comment by tanema** [comment]
The developers of this library are being very patient with you but you are coming in here without constructive criticism and strongly held *incorrect* opinions and making it hard for the developers to maintain this library. When you write *sigh* or *puke* you are taking energy away from the developers. Your attitude is toxic. Please take a moment and consider the impact of your actions.

As for code style, one of the main principals of writing go is its consistent code style. It makes any repo maintainable by any Go developer. It is for the better of the community. I appreciate that things are done differently in other communities, and I implement them in other communities technologies, but when you are actively participating in an open source community you normally follow their guidelines.

**Comment by malashin** [comment]
I understand the issue but it was vaguely decided to use Go's guidelines in this library and there is still a lot to do in this regard. And I don't think that it's handled in a good way. Package is still consider unstable with all the frequent changes to it in the master branch.

If we are actually following the guidelines then we should state what they are in the readme. Knowing what naming convention is used helps with finding the proper function or constant names.

All the breaking changes since [v0.2](https://github.com/veandco/go-sdl2/releases/tag/v0.2) are kept here:
https://github.com/veandco/go-sdl2/blob/master/BREAKING.md

**Comment by veeableful** [comment]
I really am sorry that a lot of troubles seems to have been caused by the API changes. The original developer did want to keep it simple in terms of naming (such as using SDL2 function names as they are without `SDL_`). However, we think that this API change will create a much better experience for Go developers using the library in the future as we're conforming to the Go coding guidelines.

We're also going to use a working versioning system so in the future so you will be able to use the major version that has worked for you while we're make breaking changes on the next major version. Of course, we will try to keep the breaking changes less and less the more time passes by. If we do make them, it should be for either ergonomic or functional reasons :relaxed:
