### ISSUE TITLE
Implement go's image and image/draw interfaces

### ISSUE THREAD

**Issue by akiross** [veandco/go-sdl2#365]
Hello,
I would like to propose to implement the [image.Image](https://golang.org/pkg/image/#Image) and [https://golang.org/pkg/image/draw/#Image](draw.Image) for sdl.Surface.

Actually, I am a bit surprised they are not already implemented: it is not so common among programming languages to have a standardized package for managing images and color, but go does and I think you should take advantage of it.

The reason for this proposal is that it should not take much effort, but it should instantly give benefit and access to a wide range of packages that already use such interfaces. For instance, the go packages themselves, as well as rendering libraries such as `https://github.com/llgcode/draw2d` (given that SDL rendering is quite limited).

I think that one might object that this is not part of the original SDL, but I think that it is important for a library to be well integrated in the language's ecosystem.

**Comment by veeableful** [comment]
Hi @akiross!

I definitely agree that we should provide such interfaces if it means the binding feels more natural for the programming language. There is actually another branch where I was working on that but unfortunately hasn't been continued for awhile.

Are you proposing to implement them yourself? If not, I can work on that. Thanks for the reminder either way!

**Comment by veeableful** [comment]
Hi @akiross,

Yeah, it probably needs certain degree of SDL2 knowledge (which I got to admit: I'm not anywhere near an expert myself). I haven't worked on that code for awhile and probably need to set aside some time on Saturday to get into it again and properly work on this.

For the Surface locking, maybe we can change the existing `Lock()` method. Currently it only returns an error and the user would have to manually call `Pixels()` to modify it. Maybe we can make it more efficient by directly returning a type that implements the `Image` interface. But Go doesn't have destructor, so I guess we have to remember to use something like `defer lock.Unlock()` to unlock the surface. Now I really wish Go had a destructor :(

As an example:
```go
surface, _ := window.GetSurface()
pixels, _ := surface.Lock() // pixels is a type that implements image.Image
defer surface.Unlock()
// do something to the pixels
```

instead of:
```go
surface, _ := window.GetSurface()
surface.Lock()
pixels := surface.Pixels()  // pixels is an array of bytes
defer surface.Unlock()
// do something to the pixels
```

**Comment by veeableful** [comment]
I think it's fine as long as we implement the interface correctly. It's up to the other libraries to make use of them. My guess is they did it that way for performance reasons.

I think the code you did looks fine! Would you like to open a pull request to merge it?

**Comment by akiross** [comment]
That's true and I suspect that as well.

Regarding my code, I'm not really happy with it. If it is no rush, I will have time to work on it later this month and I plan to review it thoroughly and have it support other formats as well (e.g. palettes).

**Comment by veeableful** [comment]
Yes, definitely! Take as much time as you need @akiross. I really appreciate you working on this!

**Comment by akiross** [comment]
I created a PR for this #369, although it does not include the support for palettes.
