### ISSUE TITLE
Strange messages from sensor

### ISSUE THREAD

**Issue by 3auris** [veandco/go-sdl2#366]
After dcef35236774244fd0d2ee001ce75940d166b50b commit when building go application there appear a lot of messages:

![screenshot from 2018-11-11 22-57-34](https://user-images.githubusercontent.com/7118780/48318204-65168600-e605-11e8-86bf-c623951368f5.png)

Is the only way to remove these messages is to upgrade SDL2 to 2.0.9 version?

**Comment by FriskyDev** [comment]
The default package on Ubuntu for libsdl2-dev has not made it to 2.0.9. As a result, if you attempt to use go-sdl2 on Ubuntu, you are greeted with lots of #pragma messages.

Is there a way to just disable and make unavailable the things that are not supported, such that if you try to use them, you get an error then, instead of just for attempting to use anything in the library?

**Comment by veeableful** [comment]
Hi @3auris and @FriskyDev, I've disabled the warnings by default with this commit e081255f. You can see the commit message if you want to know how to re-enable it.

If people think errors is a good idea, I'll probably think about how to add that option too! For now though, I think warnings are enough.

**Comment by FriskyDev** [comment]
Awesome, thanks! I'll take a look as soon as I can get back to that environment. 👍

**Comment by 3auris** [comment]
For me, it's a great solution, thank you very much @veeableful

**Comment by FriskyDev** [comment]
This works for me. Thanks for doing this!

**Comment by veeableful** [comment]
Yay! I'll close this for now but let me know if there's any issue!
