### ISSUE TITLE
Friendly color names

### ISSUE THREAD

**Issue by dre2004** [veandco/go-sdl2#434]
Hello,

Is it possible to have a "friendly" set of color names? 

Something similar to this [Basic Colors](https://github.com/gen2brain/raylib-go/blob/master/raylib/raylib.go#L396-L449).

I have been able to take that code and modify it slightly for my project but currently I still have to reference each color individually as opposed to just passing LightGray where a RGBA value is expected.

Are colors always hard coded each time you want to use it or is there another preferred way of mapping these ?

**Comment by Noofbiz** [comment]
There's a colornames package in golang.org/x/image that has a ton of color names, all the ones that you'll find in a browser / the svg spec. https://godoc.org/golang.org/x/image/colornames

**Comment by dre2004** [comment]
Thanks!

**Comment by dev-abir** [comment]
Each color in colornames package is of type color.RGBA.
sdl.Color is also of type color.RGBA. [(see this)](https://github.com/veandco/go-sdl2/blob/9dccbdb139b8af63c31a3b46d37cc5629e18ab86/sdl/pixels.go#L74)
Now, if you try to display a simple rect using:
```
rect := sdl.Rect{0, 0, 200, 200}
surface.FillRect(&rect, sdl.Color(colornames.Red).Uint32())
```
You will see a blue rect, instead of red. I think there is a problem with the ```Uint32()``` method
