### ISSUE TITLE
What is the state of a full go sdl port and how do I get involved?

### ISSUE THREAD

**Issue by paked** [veandco/go-sdl2#56]
Two things:
* I see in the readme that there is talk, and a notion that a full go port of SDL could (and potentially should) be done. I feel this is the next step in go game (and other graphical application) development, and would love to be around if it happens.

* Is their is an IRC channel or a website where I could keep posted, get stuck into the community or perhaps contribute some code?

*Note:* added this as an issue as i'm not quite sure where else to put it :)

**Comment by robzan8** [comment]
News? :)

**Comment by jackyb** [comment]
Hi @robzan8, it will be released for public (so they can suggest and improve things) once it's ready.

**Comment by paked** [comment]
Is there a time frame yet?

**Comment by jackyb** [comment]
@paked I'm hoping to release it in pre-alpha state at the end of April simply for release sake so people can take a look at it and contribute. It'll only have Linux/X11 part implemented so it won't be ready for general use, however people who contribute will be able to implement (or change) the generic interfaces for other OSes and display servers.

**Comment by robzan8** [comment]
While having everything ported to Go would be great, it looks to me that it would be a tremendous amount of work that may never get to a release (depending on how many people are willing to contribute). Do you think it would be possible (and make sense) to create a Go-style API on top of the C bindings and link everything statically? I mean: create a big fat .syso object containing sdl and dependencies that works on debian and derivatives, so that the user can "go get" everything quickly (without installing sdl), while still giving the possibility to link dynamically for people that have other linux distributions. Then in the future it would still be possible to gradually port to Go one module at a time under the hood.
Is it even possible to put everything together statically and make it work without having sdl installed on the system?
(I'm very interested in making gui applications happen in Go, but I'm afraid I don't have enough knowledge yet, just tell me if I'm bothering you with these questions and I will go away :) )

**Comment by Dashed** [comment]
@jackyb Is this already released somewhere?
