### ISSUE TITLE
int vs int32

### ISSUE THREAD

**Issue by slevin** [veandco/go-sdl2#99]
I've been writing some simple code and finding I'm doing a lot of casting to int32 which are used by Rect and Point. And used in lots of functions. However, several other functions like CreateWindow and Texture.Query work with regular ints. The Go compiler wants to do int by default and seems to be pretty strict about requiring explicit casting.

Going deeper, I see that SDL2 C code just uses int which is "platform dependent" but guaranteed to be at least 16bits. So if the C code is compiling to use the native word side by default, then I'm thinking the Go version should also use just plain int in all cases where the C code uses plain int. Thus reducing unnecessary casting.

I understand this would change the interface, but I think it would be a change for the better. People on 32bit machines would get both the C code and Go code compiled to 32bit values and people on 64bit machines would get their version.

I'm happy to submit a pull request if you support this idea.

**Comment by PhiCode** [comment]
Golang's Int on 64 bit machines is 8 bytes.
Methods which return or accept an Integer could be changed easily.
Structures which are passed to SDL need to adhere to the ABI of the C structures.
Otherwise all structs would need to go through a translation layer.

I recently fixed (almost) all struct ABIs, see: https://github.com/veandco/go-sdl2/blob/master/sdl/struct_test.go

In general I agree that reducing type casts would be nice. On the other hand go ints *do* have different width on 32 and 64 bit systems.

**Comment by slevin** [comment]
I see. I was mistakenly under the assumption that C ints would be 64bits on a 64bit machines. I missed that you were doing casting into and out of Go ints in parameters and return values. I guess translating structs would be too much a performance hit? And its not clear making everything int32 (parameters and return values) would be less casting or more convenient even if that might make the api more consistent.

**Comment by PhiCode** [comment]
I contributed the unit tests and fixes because I ran into some misaligned structures while developing some little test applications.

From an architectural point of view I believe that a translation layer would make a lot of sense.
For example I did not fix the 'AudioCVT' structure because CGO has a hard time dealing with packed structures.

Since I only fixed existing code I did not add real struct translations (purely out of laziness :) )
My measurement so far have shown that crossing the barrier between C and GO through CGO is quite expensive. More than a very few thousand calls per frame is unrealistic.
So I believe that a translation layer would add few enough overhead to be noise against the CGO call overhead. Of course benchmarks would be required to verify this.

This could be a nice place to try out go:generate :)

@jackyb: Do you have any design in mind for this or similar issues?

**Comment by krux02** [comment]
I actually would suggest, to chage the API to int whenever possible. For example in `timer.go` GetTicks and Delay could be changed to use `int` instead of `uint32`. For the Rect API, I do suggest, to implement both Rect and C compatible non exported rect32 for communication. I think a rect is small enough to be casted back and forth on calls, where it matters. All functions that do clipping and other calculations on rects should be ported to tative go, to prevent CGO calls.
